import type { Metadata } from "next";
import { Kanit } from "next/font/google";

import "./globals.css";
import Header from "@/components/Header";

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", '500', '600', '700', '800', "900" ],
  variable: '--font-kanit'
  
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} font-sans bg-primary text-white leading-loose`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
